apiVersion: 1
datasources:
    - name: SeventySix-API
      type: grafana-infinity-datasource
      access: proxy
      url: http://seventysix-api-dev:8080
      isDefault: false
      editable: true
      jsonData:
          httpMethod: GET
          apiKeyConfigured: false
          authType: none

