apiVersion: 1
datasources:
    - name: SeventySix-API
      type: grafana-infinity-datasource
      access: proxy
      # Uses Docker service name for DNS resolution
      # Dev: seventysix-api, Prod: api (if needed, configure via Grafana UI)
      url: http://seventysix-api:8080
      isDefault: false
      editable: true
      jsonData:
          httpMethod: GET
          apiKeyConfigured: false
          authType: none
